version: "3.1"

services:
  dbmysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
        - ./data/mysql:/docker-entrypoint-initdb.d
    ports:
        - 3307:3306
    environment:
        MYSQL_ROOT_PASSWORD: ETxGkUcEZM7M22tP5
        MYSQL_DATABASE: kecommerce
  appapi:
    image: appapi
    build:
      context: ./api-app
    restart: always
    ports:
      - 3003:3003
    depends_on:
      - dbmysql
    links:
      - dbmysql
  shopapi:
    image: shopapi
    build:
      context: ./api-shop-admin
    restart: always
    ports:
      - 3002:3002
    depends_on:
      - dbmysql
    links:
      - dbmysql
  adminapi:
    image: adminapi
    build:
      context: ./api-system-admin
    restart: always
    ports:
      - 3004:3004
    depends_on:
      - dbmysql
    links:
      - dbmysql
volumes:
  db_data: {}
