version: "3.1"

services:
  dbmysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
        - ./data/mysql:/docker-entrypoint-initdb.d
    ports:
        - 3307:3306
    environment:
        MYSQL_ROOT_PASSWORD: ETxGkUcEZM7M22tP5
        MYSQL_DATABASE: kecommerce
  appapi:
    image: appapi
    build:
      context: ./api-app
    restart: always
    ports:
      - 3003:3003
    depends_on:
      - dbmysql
    links:
      - dbmysql
volumes:
  db_data: {}
